name: Docker Image CI V@

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name : docker login 
      env :
        DOCKER_USER : toneruiz
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_LOGIN_PASSWORD }}
      run :
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  

    - name : echo dockerhub rep
      run : echo ${{ secrets.DOCKERHUB_AUTHORIZATION_IMAGE}}
    - name : list current dir
      run : ls truiz_docker_exam/test_authentication/ 
    - name : Build Docker Authentication Image 
      run: cd truiz_docker_exam/test_authentication/ && docker build . -t toneruiz/mlops-cicd-demo-authentication:latest && python3 -m pytest test_authentication.py && cd ../../
    - name : Build Docker Authorization Image 
      run: cd truiz_docker_exam/test_authorization/ && docker build . -t toneruiz/mlops-cicd-demo-authorization:latest && python3 -m pytest test_authentication.py && cd ../../  
    - name : Build Docker Content Image 
      run: cd truiz_docker_exam/test_content/ && docker build . -t toneruiz/mlops-cicd-demo-content:latest && python3 -m pytest test_authentication.py && cd ../../  
    - name : Docker push authentication
      run : docker push toneruiz/mlops-cicd-demo-authentication:latest
    - name : Docker push authorization
      run : docker push toneruiz/mlops-cicd-demo-authorization:latest
    - name : Docker push content
      run : docker push toneruiz/mlops-cicd-demo-content:latest

   
    # - name: Build the Authorization Docker image
    #   run: docker build truiz_docker_exam/test_authorization/ --file Dockerfile --tag truiz-authorization-image:latest
 
    # - name: Build the Authentication Docker image
    #   run: docker build truiz_docker_exam/test_authentication/ --file Dockerfile --tag truiz-authentication-image:latest

 
    # - name: Build the Content Docker image
    #   run: docker build truiz_docker_exam/test_content/ --file Dockerfile --tag truiz-content-image:latest
      
    # - name: Build and Push Authorization Docker Image
    #   uses: mr-smithers-excellent/docker-build-push@v4
    #   with:
    #     image:  ${{ secrets.DOCKERHUB_AUTHORIZATION_IMAGE}} # nanajanashia/demo-app
    #     registry: docker.io
    #     username: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}
    #     password: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
      
    # - name: Build and Push Content Docker Image
    #   uses: mr-smithers-excellent/docker-build-push@v4
    #   with:
    #     image:  ${{ secrets.DOCKERHUB_CONTENT_IMAGE}} # nanajanashia/demo-app
    #     registry: docker.io
    #     username: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}
    #     password: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
    
    # - name: Build and Push Authentication Docker Image
    #   uses: mr-smithers-excellent/docker-build-push@v4
    #   with:
    #     image:  ${{ secrets.DOCKERHUB_AUTHENTICATION_IMAGE}} # nanajanashia/demo-app
    #     registry: docker.io
    #     username: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}
    #     password: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
